name: Docker PostGIS CI

on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 * * 1'

defaults:
  run:
    shell: bash

jobs:
  
  make-docker-images:
    strategy:
      matrix:
        postgres: [9.5, 9.6, 10, 11, 12, 13]
        postgis: ['2.5', '3.1']
        variant: [default, alpine]
        exclude:
          - postgres: 13
            postgis: '2.5'
          - postgres: 9.5
            postgis: '3.1'
        include:
          - postgres: 9.5
            postgis: '3.0'
            variant: default
          - postgres: 9.5
            postgis: '3.0'
            variant: alpine
          - postgres: 12
            postgis: master
            variant: default
          - postgres: 13
            postgis: master
            variant: default
    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }} variant ${{ matrix.variant }}
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.postgis == 'master' }}
    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}
      VARIANT: ${{ matrix.variant }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Build docker image for ${{ env.VERSION }} ${{ env.VARIANT }}
      run: make test

    - name: Login to dockerhub
      if: ${{  (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request')  }}
      env:
        DOCKERHUB_ALIYUN_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_ALIYUN_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      run: docker login -u $DOCKERHUB_ALIYUN_USERNAME -p $DOCKERHUB_ALIYUN_PASSWORD registry.cn-hangzhou.aliyuncs.com

    - name: Push docker image to dockerhub
      if: ${{  (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request')  }}
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      run: make push

